export default {
  events: [/*
    {
      gameId: "Fortnite",
      eventId: "LunarLiveEventS8Ending",
      regions: ["EU"],
      regionMappings: {},
      platforms: [
        "XboxOneGDK",
        "PS4",
        "XboxOne",
        "XSX",
        "Android",
        "PS5",
        "Switch",
        "Windows",
      ],
      platformMappings: {},
      displayDataId: "LunarLiveEventS8Ending",
      eventGroup: "",
      announcementTime: "2020-02-03T00:00:00.000Z",
      appId: null,
      environment: null,
      metadata: {
        minimumAccountLevel: 0,
      },
      eventWindows: [
        {
          eventWindowId: "LunarLiveEventS8Ending_Event1",
          eventTemplateId: "EventTemplate_LunarLiveEventS8Ending",
          countdownBeginTime: "2020-02-03T00:00:00.000Z",
          beginTime: "2024-02-03T12:00:00.000Z",
          endTime: "2024-08-19T18:00:00.000Z",
          blackoutPeriods: [],
          round: 0,
          payoutDelay: 0,
          isTBD: false,
          canLiveSpectate: false,
          scoreLocations: [],
          visibility: "unlocked",
          requireAllTokens: [],
          requireAnyTokens: [],
          requireNoneTokensCaller: [],
          requireAllTokensCaller: [],
          requireAnyTokensCaller: [],
          additionalRequirements: [],
          teammateEligibility: "all",
          metadata: {
            ServerReplays: true,
            RoundType: "Qualifiers",
          },
        },
      ],
      beginTime: "2024-08-19T18:00:00.000Z",
      endTime: "2024-08-19T18:30:00.000Z",
    },
  ],
  player: {},
  scores: [],
  templates: [
    {
      gameId: "Fortnite",
      eventTemplateId: "EventTemplate_LunarBetaEvent",
      playlistId: "Playlist_Music_High",
      matchCap: 0,
      liveSessionAttributes: [],
      scoringRules: [],
    },
  */],
};
